version: '3.7'

services:
  db:
    image: postgres
    ports:
      - "5431:5431"
    expose:
      - 5431
    volumes:
      - ./:/code
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: db
  ebms_db:
    image: rapidfort/microsoft-sql-server-2019-ib:latest
    hostname: db
    domainname: db
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "1433:1433"
  web:
    build: .
    env_file:
      - .env
    command: sh -c "chmod +x ./entrypoint.sh && ./entrypoint.sh"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - ebms_db

volumes:
  static_volume: