from sqlalchemy import String, Integer, DATE, Boolean, Numeric
from sqlalchemy.orm import Mapped, mapped_column

from common.models import EBMSBase


class Tasks(EBMSBase):
    autoid: Mapped[int] = mapped_column('AUTOID', String(50), primary_key=True)
    task_guid: Mapped[str] = mapped_column('TASK_GUID', String(36))
    recno5: Mapped[int] = mapped_column('RECNO5', Integer)
    cust_id: Mapped[str] = mapped_column('CUST_ID', String(10))
    document: Mapped[str] = mapped_column('DOCUMENT', String(15))
    doc_type: Mapped[str] = mapped_column('DOC_TYPE', String(1))
    dic_stamp: Mapped[str] = mapped_column('DIC_STAMP', String(10))
    emp_id: Mapped[str] = mapped_column('EMP_ID', String(10))
    start_date: Mapped[str] = mapped_column('START_DATE', DATE)
    start_time: Mapped[str] = mapped_column('START_TIME', String(5))
    end_date: Mapped[str] = mapped_column('END_DATE', DATE)
    end_time: Mapped[str] = mapped_column('END_TIME', String(5))
    flex_sched: Mapped[str] = mapped_column('FLEX_SCHED', Boolean)
    f_start_d: Mapped[str] = mapped_column('F_START_D', DATE)
    f_end_d: Mapped[str] = mapped_column('F_END_D', DATE)
    bill_time: Mapped[str] = mapped_column('BILL_TIME', Numeric(9, 2))
    descr: Mapped[str] = mapped_column('DESCR', String(75))
    note: Mapped[str] = mapped_column('NOTE', String(50))
    id: Mapped[int] = mapped_column('ID', String(10))
    approved: Mapped[str] = mapped_column('APPROVED', String(20))
    preapprovd: Mapped[str] = mapped_column('PREAPPROVD', Boolean)
    completed: Mapped[str] = mapped_column('COMPLETED', String(20))
    due_by: Mapped[str] = mapped_column('DUE_BY', DATE)
    workcode: Mapped[str] = mapped_column('WORKCODE', String(10))
    item: Mapped[str] = mapped_column('ITEM', String(24))
    ticket: Mapped[str] = mapped_column('TICKET', String(15))
    doc_stat: Mapped[str] = mapped_column('DOC_STAT', String(1))
    type: Mapped[str] = mapped_column('TYPE', String(35))
    author: Mapped[str] = mapped_column('AUTHOR', String(20))
    create_d: Mapped[str] = mapped_column('CREATE_D', DATE)
    act_time: Mapped[str] = mapped_column('ACT_TIME', Numeric(9, 2))
    priority: Mapped[str] = mapped_column('PRIORITY', String(10))
    manager: Mapped[str] = mapped_column('MANAGER', String(35))
    status: Mapped[str] = mapped_column('STATUS', String(25))
    change_d: Mapped[str] = mapped_column('CHANGE_D', DATE)
    change_u: Mapped[str] = mapped_column('CHANGE_U', DATE)
    cust_note: Mapped[str] = mapped_column('CUST_NOTE', Boolean)
    in_house: Mapped[str] = mapped_column('IN_HOUSE', Integer)
    base_type: Mapped[str] = mapped_column('BASE_TYPE', String(1))
    bonus_appl: Mapped[str] = mapped_column('BONUS_APPL', Boolean)
    act_bill: Mapped[str] = mapped_column('ACT_BILL', Numeric(9, 2))
    wait_part: Mapped[str] = mapped_column('WAIT_PART', Boolean)
    comp_u: Mapped[str] = mapped_column('COMP_U', String(20))
    comp_d: Mapped[str] = mapped_column('COMP_D', DATE)
    estimate: Mapped[str] = mapped_column('ESTIMATE', Boolean)
    estimated: Mapped[str] = mapped_column('ESTIMATED', Numeric(9, 3))
    hours: Mapped[str] = mapped_column('HOURS', Numeric(9, 3))
    worktreeid: Mapped[str] = mapped_column('WORKTREED', String(5))
    updatequan: Mapped[str] = mapped_column('UPDATEQUAN', Boolean)
    update_bt: Mapped[str] = mapped_column('UPDATE_BT', Boolean)
    hrsperunit: Mapped[str] = mapped_column('HRSPERUNIT', Numeric(9, 2))
    app_conf: Mapped[str] = mapped_column('APP_CONF', Boolean)
    job_id: Mapped[str] = mapped_column('JOB_ID', String(10))
    jobstg_id: Mapped[str] = mapped_column('JOBSTG_ID', String(15))
    app_to_pro: Mapped[str] = mapped_column('APP_TO_PRO', Boolean)
    serial_no: Mapped[str] = mapped_column('SERIAL_NO', String(24))
    reg_item: Mapped[str] = mapped_column('REG_ITEM', String(24))
    doc_aid: Mapped[str] = mapped_column('DOC_AID', String(16))
    int_note: Mapped[str] = mapped_column('INT_NOTE', String(50))
    due_time: Mapped[str] = mapped_column('DUE_TIME', String(5))
    c_dept: Mapped[str] = mapped_column('C_DEPT', String(3))
    task_prn: Mapped[str] = mapped_column('TASK_PRN', Boolean)
    rto_bill: Mapped[str] = mapped_column('RTO_BILL', Boolean)
    quote_n: Mapped[str] = mapped_column('QUOTE_N', String(15))
    cust_follw: Mapped[str] = mapped_column('CUST_FOLLW', String(12))
    custfolw_u: Mapped[str] = mapped_column('CUSTFOLW_U', String(20))
    custfolw_d: Mapped[str] = mapped_column('CUSTFOLW_D', DATE)
    approved_d: Mapped[str] = mapped_column('APPROVED_D', DATE)
    phase_aid: Mapped[str] = mapped_column('PHASE_AID', String(16))
    pipe_phase: Mapped[str] = mapped_column('PIPE_PHASE', String(24))
    pipe_rank: Mapped[str] = mapped_column('PIPE_RANK', String(5))
    clk_in_emp: Mapped[str] = mapped_column('CLK_IN_EMP', String(20))
    cntct_aid: Mapped[str] = mapped_column('CNTCT_AID', String(16))
    rootticket: Mapped[str] = mapped_column('ROOTTICKET', String(15))
    csend_date: Mapped[str] = mapped_column('CSEND_DATE', DATE)
    csend_time: Mapped[str] = mapped_column('CSEND_TIME', String(5))
    csend_mes: Mapped[str] = mapped_column('CSEND_MES', String(50))
    assign_emp: Mapped[str] = mapped_column('ASSIGN_EMP', String(20))
    externalid: Mapped[str] = mapped_column('EXTERNALID', String(50))
